export const galleryData = [
  {
    title: "The Himalayas",
    subtitle: "Where Earth Meets Sky",
    location: "Northern India",
    dec: "Towering peaks draped in eternal snow, where the air is thin and the silence speaks in ancient tongues. The Himalayas are not just mountains — they are the spine of India's spiritual journey.",
    url: "https://images.unsplash.com/photo-1607836046730-3317bd58a31b?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#3b82f6",
  },
  {
    title: "Varanasi Ghats",
    subtitle: "The City of Light",
    location: "Uttar Pradesh",
    dec: "For millennia, pilgrims have gathered at dawn on these ancient steps. The Ganges flows eternal as prayers rise with incense smoke a living tableau of life, death, and rebirth.",
    url: "https://images.unsplash.com/photo-1571536802807-30451e3955d8?q=80&w=1220&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#fbbf24",
  },
  {
    title: "Kerala Backwaters",
    subtitle: "Venice of the East",
    location: "Kerala",
    dec: "Emerald waterways weave through palm-fringed villages, where houseboats drift lazily under coconut canopies. Time slows down as the sun paints the lagoons in gold and amber.",
    url: "https://images.unsplash.com/photo-1609828913552-f9138ed9e42d?q=80&w=1194&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#10b981",
  },
  {
    title: "Hawa Mahal",
    subtitle: "The Palace of Winds",
    location: "Jaipur, Rajasthan",
    dec: "A sandstone symphony of 953 windows, built so royal ladies could watch street processions unseen. Each carved jharokha tells stories of romance, war, and royal splendor.",
    url: "https://images.unsplash.com/photo-1705861145876-2efd5e0392a5?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#f87171",
  },
  {
    title: "Taj Mahal",
    subtitle: "A Tear on the Cheek of Time",
    location: "Agra, Uttar Pradesh",
    dec: "Built from the grief of an emperor for his beloved queen. White marble that changes mood with the light blushing at dawn, glowing at noon, ethereal under moonlight.",
    url: "https://images.unsplash.com/photo-1587135941948-670b381f08ce?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#eab308",
  },
  {
    title: "India Gate",
    subtitle: "A Nation's Salute",
    location: "New Delhi",
    dec: "A solemn arch that honors the soldiers who laid down their lives. By day, it stands proud against the sky; by night, it glows with the nation's gratitude.",
    url: "https://images.unsplash.com/photo-1705861144478-40b4c1157a24?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    color: "#fcd34d",
  },
];
